#2932 :safety_vest: Validação para verificar dados
mapasculturais/mapasculturais pull request #2933
Opened 2023-08-02 14:42 UTC by Junior-Shyko

Caso não tenha dados, é add um valor padrao p/ renderizar a página.

2023-08-02 23:13 UTC, Junior-Shyko commented
@Junior-Shyko Adorei os bots aqui.

2023-10-26 19:09 UTC, lpirola approved these changes

2023-10-26 19:24 UTC, rafaelchavesfreitas requested changes
rever o código da linha 61 até a linha 66.

2023-10-26 19:24 UTC, rafaelchavesfreitas commented on src/protected/application/lib/modules/Charts/layouts/parts/charts/line.php
> +($isSeriesData) ?? $widthData =  $series[0]['data'];
acredito que o operador correto aqui seja o  `?:` pois com o operador `??` o `$widthData =  $series[0]['data'];` nunca será executado, como exemplificado nos prints abaixo:

![image](https://github.com/mapasculturais/mapasculturais/assets/1181261/635498dc-9ea2-4f47-880b-5aa692140739)

![image](https://github.com/mapasculturais/mapasculturais/assets/1181261/2fa33047-c282-4d24-8537-9fcb4472eb19)

2023-10-26 19:24 UTC, rafaelchavesfreitas commented on src/protected/application/lib/modules/Charts/layouts/parts/charts/line.php
> +($isSeriesData) ?? $widthData =  $series[0]['data'];
além disso, não seria 
```PHP
$widthData = $count_data($series[0]['data'])
```
?

2024-07-01 22:49 UTC, closed without merging